import { describe, expect, it } from 'vitest'

import { mergeRelatedArticles } from '@/components/student-hub/articles/detail/relatedArticles'
import { normalizePastedLexical, renderArticleHtml, slugifyHeading } from '@/lib/articleContent'
import type { Article } from '@/payload-types'

function article(partial: Partial<Article> & Pick<Article, 'slug' | 'title' | 'category'>): Article {
  return {
    id: partial.id ?? 1,
    excerpt: partial.excerpt ?? 'Summary',
    authorName: partial.authorName ?? 'Author',
    updatedAt: '2026-08-16T00:00:00.000Z',
    createdAt: '2026-08-16T00:00:00.000Z',
    ...partial,
  } as Article
}

describe('article content rendering', () => {
  it('slugifies heading text for TOC anchors', () => {
    expect(slugifyHeading('What Is a Deepfake?')).toBe('what-is-a-deepfake')
  })

  it('renders CMS headings and paragraphs instead of a single text block', () => {
    const { html, sections } = renderArticleHtml({
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            version: 1,
            children: [{ type: 'text', text: 'A Kerala victim received a WhatsApp video call.', version: 1 }],
          },
          {
            type: 'heading',
            tag: 'h2',
            version: 1,
            children: [{ type: 'text', text: 'What Is a Deepfake?', version: 1 }],
          },
          {
            type: 'paragraph',
            version: 1,
            children: [{ type: 'text', text: 'A deepfake is synthetic media generated by AI.', version: 1 }],
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    })

    expect(html).toContain('<h2')
    expect(html).toMatch(/<h2[^>]*id="what-is-a-deepfake"/)
    expect(html).toContain('What Is a Deepfake?')
    expect(html).toContain('A deepfake is synthetic media generated by AI.')
    expect(sections).toEqual([{ id: 'what-is-a-deepfake', title: 'What Is a Deepfake?' }])
  })

  it('promotes line-break headings pasted from docs or PDFs', () => {
    const normalized = normalizePastedLexical({
      root: {
        children: [
          {
            type: 'paragraph',
            children: [
              { type: 'text', text: 'Intro sentence about the fraud case in Kerala.' },
              { type: 'linebreak' },
              { type: 'text', text: 'What Is a Deepfake?' },
              { type: 'linebreak' },
              { type: 'text', text: 'A deepfake is synthetic media generated by AI models.' },
            ],
          },
        ],
      },
    })

    expect(normalized?.root?.children?.map((node) => node.type)).toEqual([
      'paragraph',
      'heading',
      'paragraph',
    ])
  })
})

describe('related articles', () => {
  it('prefers the same category and fills with recent articles when needed', () => {
    const related = mergeRelatedArticles(
      [
        article({
          id: 2,
          slug: 'same-domain-one',
          title: 'Same Domain One',
          category: 'digitalForensics',
        }),
      ],
      [
        article({
          id: 2,
          slug: 'same-domain-one',
          title: 'Same Domain One',
          category: 'digitalForensics',
        }),
        article({
          id: 3,
          slug: 'recent-two',
          title: 'Recent Two',
          category: 'ballistics',
        }),
        article({
          id: 4,
          slug: 'recent-three',
          title: 'Recent Three',
          category: 'psychology',
        }),
      ],
      'current-article',
    )

    expect(related.map((item) => item.slug)).toEqual([
      'same-domain-one',
      'recent-two',
      'recent-three',
    ])
  })

  it('uses recent articles when no other article exists in the same domain', () => {
    const related = mergeRelatedArticles(
      [],
      [
        article({
          id: 8,
          slug: 'recent-a',
          title: 'Recent A',
          category: 'general',
        }),
        article({
          id: 9,
          slug: 'recent-b',
          title: 'Recent B',
          category: 'dna',
        }),
      ],
      'current-article',
    )

    expect(related.map((item) => item.slug)).toEqual(['recent-a', 'recent-b'])
  })
})
