import type { ArticleListItem, FeaturedArticle, TopicFilter } from '@/components/student-hub/articles/types'

export const topicFilters: TopicFilter[] = [
  { id: 'all', label: 'All Topics', value: 'all' },
  { id: 'odontology', label: 'Forensic Odontology', value: 'odontology', icon: '🦷' },
  { id: 'toxicology', label: 'Toxicology', value: 'toxicology' },
  { id: 'dna', label: 'DNA', value: 'dna' },
  { id: 'digitalForensics', label: 'Digital Forensics', value: 'digitalForensics' },
]

export const defaultFeatured: FeaturedArticle = {
  id: 'featured-1',
  slug: 'ai-driven-digital-forensics',
  title: 'Advancements in Digital Forensics: AI-Driven Evidence Analysis',
  excerpt:
    'How machine-assisted workflows are transforming digital evidence triage, validation, and courtroom presentation while preserving chain of custody.',
  category: 'digitalForensics',
  categoryLabel: 'Digital Forensics',
  authorName: 'Dr. A. Sharma',
  authorTitle: 'Cyber Expert',
  readTimeMinutes: 12,
  publishedDate: '2023-11-15',
}

export const defaultArticles: ArticleListItem[] = [
  {
    id: '1',
    slug: 'post-mortem-interval',
    title: 'Understanding Post-Mortem Interval through Entomology',
    excerpt: 'A practical overview of insect succession patterns and their application in time-since-death estimation.',
    category: 'toxicology',
    categoryLabel: 'Toxicology',
    authorName: 'Dr. Mehta',
    readTimeMinutes: 15,
  },
  {
    id: '2',
    slug: 'ballistics-basics',
    title: 'Ballistics Basics for Crime Scene Investigators',
    excerpt: 'Firearm identification, trajectory analysis, and documentation standards for field teams.',
    category: 'ballistics',
    categoryLabel: 'Ballistics',
    authorName: 'Mr. Vijay',
    readTimeMinutes: 11,
  },
  {
    id: '3',
    slug: 'forensic-psychology-interviews',
    title: 'Forensic Psychology in Witness Interviews',
    excerpt: 'Cognitive interview techniques that reduce contamination while improving recall accuracy.',
    category: 'psychology',
    categoryLabel: 'Psychology',
    authorName: 'Dr. Khan',
    readTimeMinutes: 9,
  },
  {
    id: '4',
    slug: 'dna-mixture-interpretation',
    title: 'DNA Mixture Interpretation in Complex Samples',
    excerpt: 'Probabilistic genotyping approaches for low-template and multi-contributor profiles.',
    category: 'dna',
    categoryLabel: 'DNA',
    authorName: 'Dr. Patel',
    readTimeMinutes: 18,
  },
  {
    id: '5',
    slug: 'odontology-bite-marks',
    title: 'Forensic Odontology: Bite Mark Analysis Today',
    excerpt: 'Updated guidelines on collection, imaging, and comparative analysis of dental evidence.',
    category: 'odontology',
    categoryLabel: 'Forensic Odontology',
    authorName: 'Dr. Singh',
    readTimeMinutes: 14,
  },
  {
    id: '6',
    slug: 'toxicology-screening',
    title: 'Rapid Toxicology Screening in Emergency Casework',
    excerpt: 'Immunoassay workflows and confirmatory testing pathways for clinical-legal teams.',
    category: 'toxicology',
    categoryLabel: 'Toxicology',
    authorName: 'Dr. Rao',
    readTimeMinutes: 10,
  },
  {
    id: '7',
    slug: 'mobile-device-forensics',
    title: 'Mobile Device Forensics: Extraction Best Practices',
    excerpt: 'Logical, physical, and cloud-derived artifacts in modern smartphone investigations.',
    category: 'digitalForensics',
    categoryLabel: 'Digital Forensics',
    authorName: 'Dr. A. Sharma',
    readTimeMinutes: 16,
  },
  {
    id: '8',
    slug: 'crime-scene-photography',
    title: 'Crime Scene Photography for Admissibility',
    excerpt: 'Scale, lighting, and sequential documentation techniques that withstand courtroom scrutiny.',
    category: 'general',
    categoryLabel: 'General',
    authorName: 'Mr. Rakesh Mia',
    readTimeMinutes: 8,
  },
]
