/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    aboutCertifications: AboutCertification;
    services: Service;
    galleryItems: GalleryItem;
    testimonials: Testimonial;
    scientists: Scientist;
    impactStats: ImpactStat;
    notices: Notice;
    partnersLogo: PartnersLogo;
    events: Event;
    eventRegistrations: EventRegistration;
    courseRegistrations: CourseRegistration;
    contactMessages: ContactMessage;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    aboutCertifications: AboutCertificationsSelect<false> | AboutCertificationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    galleryItems: GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    scientists: ScientistsSelect<false> | ScientistsSelect<true>;
    impactStats: ImpactStatsSelect<false> | ImpactStatsSelect<true>;
    notices: NoticesSelect<false> | NoticesSelect<true>;
    partnersLogo: PartnersLogoSelect<false> | PartnersLogoSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    courseRegistrations: CourseRegistrationsSelect<false> | CourseRegistrationsSelect<true>;
    contactMessages: ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    headerSettings: HeaderSetting;
    footerSettings: FooterSetting;
    homePage: HomePage;
    aboutPage: AboutPage;
    servicesPage: ServicesPage;
    programmesCatalog: ProgrammesCatalog;
    registrationForm: RegistrationForm;
    studentHubContent: StudentHubContent;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    headerSettings: HeaderSettingsSelect<false> | HeaderSettingsSelect<true>;
    footerSettings: FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    aboutPage: AboutPageSelect<false> | AboutPageSelect<true>;
    servicesPage: ServicesPageSelect<false> | ServicesPageSelect<true>;
    programmesCatalog: ProgrammesCatalogSelect<false> | ProgrammesCatalogSelect<true>;
    registrationForm: RegistrationFormSelect<false> | RegistrationFormSelect<true>;
    studentHubContent: StudentHubContentSelect<false> | StudentHubContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary shown in cards and listings.
   */
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category:
    | 'biologySerology'
    | 'dna'
    | 'toxicology'
    | 'ballistics'
    | 'fingerprint'
    | 'questionedDocument'
    | 'crimeScene'
    | 'forensicPhotography'
    | 'forensicMedicine'
    | 'forensicPathology'
    | 'multimediaForensics'
    | 'forensicInstrumentation'
    | 'psychology'
    | 'odontology'
    | 'forensicAnthropology'
    | 'digitalForensics'
    | 'aiMl'
    | 'forensicBiotechnology'
    | 'voiceAnalysis'
    | 'forensicAccounting'
    | 'general';
  coverImage?: (number | null) | Media;
  authorName: string;
  authorTitle?: string | null;
  authorAvatar?: (number | null) | Media;
  readTimeMinutes?: number | null;
  publishedDate?: string | null;
  /**
   * Optional second category pill (e.g. AI in Forensics).
   */
  secondaryTag?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  pullQuote?: {
    text?: string | null;
    attribution?: string | null;
  };
  authorBio?: string | null;
  /**
   * Show as Editor's Choice
   */
  featured?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Certifications and recognitions shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutCertifications".
 */
export interface AboutCertification {
  id: number;
  title: string;
  /**
   * Optional issuing authority, ministry, or institution.
   */
  issuer?: string | null;
  /**
   * Upload the certification logo or emblem. Stored through Media.
   */
  logo: number | Media;
  /**
   * Optional short note shown on the About page card.
   */
  description?: string | null;
  /**
   * Optional public URL to a certificate PDF, verification page, or proof.
   */
  certificateUrl?: string | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  icon?: (number | null) | Media;
  banner?: (number | null) | Media;
  /**
   * Short summary shown in cards.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('forensicService' | 'laboratory' | 'training' | 'consultancy') | null;
  /**
   * Heading for the capability rows on the service detail page.
   */
  helpHeading?: string | null;
  /**
   * Optional intro paragraph shown under the heading.
   */
  helpIntro?: string | null;
  /**
   * Each item is a full-width row: content on the left and thumbnail on the right.
   */
  features?:
    | {
        featureTitle: string;
        featureDescription?: string | null;
        /**
         * Optional supporting points. Enter one point per line.
         */
        featurePoints?: string | null;
        /**
         * Image shown on the right side of this row.
         */
        featureIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryItems".
 */
export interface GalleryItem {
  id: number;
  title: string;
  label: string;
  image: number | Media;
  category?: ('lab' | 'training' | 'tech' | 'events' | 'other') | null;
  published?: boolean | null;
  /**
   * Show on home page gallery.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  title: string;
  testimonial: string;
  rating: number;
  image?: (number | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add, edit, reorder, and publish people shown in Laboratory Directorate and Laboratory Members on the Services page. The same records also appear on Home and About when published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scientists".
 */
export interface Scientist {
  id: number;
  name: string;
  /**
   * Role shown under the name, for example Forensic Expert.
   */
  designation: string;
  /**
   * Directorate appears in Laboratory Directorate. Team member appears in Laboratory Members.
   */
  memberType: 'director' | 'member';
  /**
   * Badge on the profile card. Uncheck Published to hide this person from the website.
   */
  status: 'active' | 'inactive';
  bio?: string | null;
  /**
   * Square profile photo recommended.
   */
  photo?: (number | null) | Media;
  /**
   * Unpublished people are hidden from the public site.
   */
  published?: boolean | null;
  /**
   * Lower numbers appear first within the same section.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impactStats".
 */
export interface ImpactStat {
  id: number;
  label: string;
  value: string;
  description?: string | null;
  tone?: ('indigo' | 'blue' | 'purple' | 'emerald' | 'orange') | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Official announcements shown on the Notice Board page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices".
 */
export interface Notice {
  id: number;
  title: string;
  tag: 'Admission' | 'Service' | 'Results' | 'Partnership' | 'Event' | 'General';
  noticeDate: string;
  summary?: string | null;
  /**
   * Optional link for more details.
   */
  href?: string | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnersLogo".
 */
export interface PartnersLogo {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  banner?: (number | null) | Media;
  /**
   * Short summary shown in cards and listings.
   */
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventNature?: ('national' | 'international') | null;
  eventType?: ('workshop' | 'webinar' | 'conference' | 'training') | null;
  mode?: ('online' | 'offline' | 'hybrid') | null;
  startDate: string;
  endDate?: string | null;
  startTime?: string | null;
  venue?: string | null;
  registrationCategories?:
    | {
        categoryName?: string | null;
        price?: number | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  includeKitOption?: boolean | null;
  kitPrice?: number | null;
  registrationOpen?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  eventSlug: string;
  eventTitle: string;
  fullName: string;
  email: string;
  countryCode?: string | null;
  mobileNumber: string;
  address?: string | null;
  organization: string;
  designation: string;
  areaOfInterest: string;
  idProofFileName?: string | null;
  idProofFileSize?: number | null;
  registrationCategoryId: string;
  registrationCategoryName: string;
  registrationCategoryPrice: number;
  includeKit?: boolean | null;
  kitPrice?: number | null;
  /**
   * UPI / bank transaction reference.
   */
  transactionId?: string | null;
  transactionDate?: string | null;
  /**
   * e.g. 14:30
   */
  transactionTime?: string | null;
  transactionProof?: (number | null) | Media;
  totalAmount: number;
  paymentProvider?: ('manual' | 'stripe') | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'notRequired';
  registrationStatus: 'initiated' | 'confirmed' | 'cancelled' | 'contacted';
  paymentReference?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paymentConfirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseRegistrations".
 */
export interface CourseRegistration {
  id: number;
  programmeType: 'education' | 'training' | 'other';
  categorySlug?: string | null;
  categoryTitle?: string | null;
  programmeId?: string | null;
  programmeTitle: string;
  programmeDuration?: string | null;
  programmeMode?: string | null;
  fullName: string;
  email: string;
  countryCode?: string | null;
  mobileNumber: string;
  address?: string | null;
  organization?: string | null;
  designation?: string | null;
  qualification?: string | null;
  experienceLevel?: ('student' | 'beginner' | 'professional' | 'faculty') | null;
  preferredBatch?: string | null;
  message?: string | null;
  /**
   * UPI / bank transaction reference.
   */
  transactionId?: string | null;
  transactionDate?: string | null;
  /**
   * e.g. 14:30
   */
  transactionTime?: string | null;
  transactionProof?: (number | null) | Media;
  totalAmount?: number | null;
  paymentProvider?: ('manual' | 'stripe') | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'notRequired';
  registrationStatus: 'initiated' | 'confirmed' | 'cancelled' | 'contacted';
  paymentReference?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paymentConfirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactMessages".
 */
export interface ContactMessage {
  id: number;
  fullName: string;
  mobile?: string | null;
  email: string;
  subject?: string | null;
  message: string;
  status?: ('new' | 'inProgress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'superAdmin' | 'contentEditor' | 'eventManager' | 'student';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'aboutCertifications';
        value: number | AboutCertification;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'galleryItems';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'scientists';
        value: number | Scientist;
      } | null)
    | ({
        relationTo: 'impactStats';
        value: number | ImpactStat;
      } | null)
    | ({
        relationTo: 'notices';
        value: number | Notice;
      } | null)
    | ({
        relationTo: 'partnersLogo';
        value: number | PartnersLogo;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'courseRegistrations';
        value: number | CourseRegistration;
      } | null)
    | ({
        relationTo: 'contactMessages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  coverImage?: T;
  authorName?: T;
  authorTitle?: T;
  authorAvatar?: T;
  readTimeMinutes?: T;
  publishedDate?: T;
  secondaryTag?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  pullQuote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  authorBio?: T;
  featured?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutCertifications_select".
 */
export interface AboutCertificationsSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  logo?: T;
  description?: T;
  certificateUrl?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  banner?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  helpHeading?: T;
  helpIntro?: T;
  features?:
    | T
    | {
        featureTitle?: T;
        featureDescription?: T;
        featurePoints?: T;
        featureIcon?: T;
        id?: T;
      };
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryItems_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  image?: T;
  category?: T;
  published?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  testimonial?: T;
  rating?: T;
  image?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scientists_select".
 */
export interface ScientistsSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  memberType?: T;
  status?: T;
  bio?: T;
  photo?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impactStats_select".
 */
export interface ImpactStatsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  description?: T;
  tone?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notices_select".
 */
export interface NoticesSelect<T extends boolean = true> {
  title?: T;
  tag?: T;
  noticeDate?: T;
  summary?: T;
  href?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnersLogo_select".
 */
export interface PartnersLogoSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  banner?: T;
  excerpt?: T;
  description?: T;
  eventNature?: T;
  eventType?: T;
  mode?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  venue?: T;
  registrationCategories?:
    | T
    | {
        categoryName?: T;
        price?: T;
        description?: T;
        id?: T;
      };
  includeKitOption?: T;
  kitPrice?: T;
  registrationOpen?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  eventSlug?: T;
  eventTitle?: T;
  fullName?: T;
  email?: T;
  countryCode?: T;
  mobileNumber?: T;
  address?: T;
  organization?: T;
  designation?: T;
  areaOfInterest?: T;
  idProofFileName?: T;
  idProofFileSize?: T;
  registrationCategoryId?: T;
  registrationCategoryName?: T;
  registrationCategoryPrice?: T;
  includeKit?: T;
  kitPrice?: T;
  transactionId?: T;
  transactionDate?: T;
  transactionTime?: T;
  transactionProof?: T;
  totalAmount?: T;
  paymentProvider?: T;
  paymentStatus?: T;
  registrationStatus?: T;
  paymentReference?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paymentConfirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseRegistrations_select".
 */
export interface CourseRegistrationsSelect<T extends boolean = true> {
  programmeType?: T;
  categorySlug?: T;
  categoryTitle?: T;
  programmeId?: T;
  programmeTitle?: T;
  programmeDuration?: T;
  programmeMode?: T;
  fullName?: T;
  email?: T;
  countryCode?: T;
  mobileNumber?: T;
  address?: T;
  organization?: T;
  designation?: T;
  qualification?: T;
  experienceLevel?: T;
  preferredBatch?: T;
  message?: T;
  transactionId?: T;
  transactionDate?: T;
  transactionTime?: T;
  transactionProof?: T;
  totalAmount?: T;
  paymentProvider?: T;
  paymentStatus?: T;
  registrationStatus?: T;
  paymentReference?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paymentConfirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactMessages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  fullName?: T;
  mobile?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Core site identity, contact details, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Manually updated visitor count shown in the visitor bar.
   */
  totalVisitors?: number | null;
  /**
   * Google Maps embed src URL for the footer and contact page.
   */
  mapEmbedUrl?: string | null;
  /**
   * Social profile URLs — used across footer and contact page.
   */
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Top bar, branding, and main navigation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerSettings".
 */
export interface HeaderSetting {
  id: number;
  topBarEnabled?: boolean | null;
  /**
   * Phone shown in top bar. Keep in sync with Site Settings → phone.
   */
  topBarLeftText?: string | null;
  /**
   * Email shown in top bar. Keep in sync with Site Settings → email.
   */
  topBarLeftText2?: string | null;
  /**
   * Social icon links in the top bar.
   */
  topBarLeftText3?:
    | {
        icon: number | Media;
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  topBarLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  brandTitle: string;
  brandSubtitle: string;
  navItems: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer about text, link columns, and copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings".
 */
export interface FooterSetting {
  id: number;
  aboutTitle: string;
  aboutDescription: string;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home page hero and section copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  hero: {
    title: string;
    description?: string | null;
    primaryCTALabel?: string | null;
    primaryCTAUrl?: string | null;
    secondaryCTALabel?: string | null;
    secondaryCTAUrl?: string | null;
    heroImage?: (number | null) | Media;
  };
  /**
   * Headings and body copy for home page sections only.
   */
  sectionText?: {
    featuredCardsHeading?: string | null;
    servicesHeading?: string | null;
    servicesDescription?: string | null;
    eventsHeading?: string | null;
    eventsDescription?: string | null;
    aboutHeading?: string | null;
    aboutDescription1?: string | null;
    aboutDescription2?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * About page hero image and all section copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage".
 */
export interface AboutPage {
  id: number;
  hero?: {
    heroImage?: (number | null) | Media;
  };
  /**
   * Headings, body copy, and lists for the About page.
   */
  sectionText?: {
    aboutHeading?: string | null;
    aboutDescription1?: string | null;
    aboutDescription2?: string | null;
    heroEyebrow?: string | null;
    heroCtaLabel?: string | null;
    heroCtaHref?: string | null;
    heroImageAlt?: string | null;
    rakeshMessage?: string | null;
    vijayMessage?: string | null;
    founderMessage?: string | null;
    visionBadge?: string | null;
    visionTitle?: string | null;
    visionBody?: string | null;
    visionHighlight?: string | null;
    visionImageAlt?: string | null;
    missionBadge?: string | null;
    missionTitle?: string | null;
    missionBody?: string | null;
    missionHighlight?: string | null;
    missionImageAlt?: string | null;
    purposeBadge?: string | null;
    purposeTitle?: string | null;
    purposeBody?: string | null;
    purposeHighlight?: string | null;
    purposeImageAlt?: string | null;
    leadershipTitle?: string | null;
    leadershipSubtitle?: string | null;
    committeeTitle?: string | null;
    committeeSubtitle?: string | null;
    certificationsTitle?: string | null;
    certificationsSubtitle?: string | null;
    certifications?:
      | {
          icon?: string | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    valuesTitle?: string | null;
    valuesSubtitle?: string | null;
    uniqueTitle?: string | null;
    uniqueSubtitle?: string | null;
    uniqueItems?:
      | {
          text: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    activitiesTitle?: string | null;
    activitiesSubtitle?: string | null;
    activityItems?:
      | {
          text: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    expertiseTitle?: string | null;
    expertiseSubtitle?: string | null;
    expertiseItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    whyChooseTitle?: string | null;
    whyChooseSubtitle?: string | null;
    whyChooseItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pillarsTitle?: string | null;
    pillarsSubtitle?: string | null;
    qualityEthicsTitle?: string | null;
    qualityEthicsEyebrow?: string | null;
    qualityEthicsItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    researchTitle?: string | null;
    researchEyebrow?: string | null;
    researchItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    partnershipsTitle?: string | null;
    partnershipsEyebrow?: string | null;
    partnershipItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pillarProofLabels?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    membershipTitle?: string | null;
    membershipSubtitle?: string | null;
    membershipPlans?:
      | {
          title: string;
          description: string;
          href?: string | null;
          badge?: string | null;
          dark?: boolean | null;
          id?: string | null;
        }[]
      | null;
    membershipCtaLabel?: string | null;
    membershipAdvantageEyebrow?: string | null;
    membershipAdvantageTitle?: string | null;
    membershipReasons?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    roadmapTitle?: string | null;
    roadmapSubtitle?: string | null;
    roadmapEyebrow?: string | null;
    roadmapCardTitle?: string | null;
    roadmapCardBody?: string | null;
    futureRoadmapItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    awardsTitle?: string | null;
    awardsSubtitle?: string | null;
    awardsCallout?: string | null;
    awardsImageAlt1?: string | null;
    awardsImageAlt2?: string | null;
    awardsImageAlt3?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Services (AFSL) page section copy and static lists.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage".
 */
export interface ServicesPage {
  id: number;
  /**
   * Headings and body copy for the Services page.
   */
  sectionText?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroHighlight?: string | null;
    heroDescription?: string | null;
    heroCtaLabel?: string | null;
    labStatusLabel?: string | null;
    labStatusValue?: string | null;
    labCardCtaLabel?: string | null;
    infrastructureEyebrow?: string | null;
    infrastructureTitle?: string | null;
    infrastructureBody1?: string | null;
    infrastructureBody2?: string | null;
    visionTitle?: string | null;
    visionBody?: string | null;
    missionTitle?: string | null;
    missionBody?: string | null;
    directorateEyebrow?: string | null;
    directorateTitle?: string | null;
    directorateSubtitle?: string | null;
    teamEyebrow?: string | null;
    teamTitle?: string | null;
    teamSubtitle?: string | null;
    catalogEyebrow?: string | null;
    catalogTitle?: string | null;
    legalTitle?: string | null;
    legalSubtitle?: string | null;
    legalDescription?: string | null;
    legalCtaLabel?: string | null;
    legalCtaSubtext?: string | null;
    kitsEyebrow?: string | null;
    kitsTitle?: string | null;
    kitsDescription?: string | null;
    trainingTitle?: string | null;
    researchTitle?: string | null;
    inquiryEyebrow?: string | null;
    inquiryTitle?: string | null;
    inquiryDescription?: string | null;
    priorityHelplineLabel?: string | null;
    reportVerificationLabel?: string | null;
    certificationStats?:
      | {
          label: string;
          caption: string;
          id?: string | null;
        }[]
      | null;
    kitCards?:
      | {
          title: string;
          icon?: ('Box' | 'Fingerprint' | 'ClipboardList' | 'FileSearch' | 'FlaskConical' | 'Beaker' | 'Users') | null;
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    researchItems?:
      | {
          num: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    trainingCards?:
      | {
          title: string;
          desc: string;
          cta: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Education and training programme categories and fallbacks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmesCatalog".
 */
export interface ProgrammesCatalog {
  id: number;
  educationCategories?:
    | {
        slug: string;
        icon: string;
        title: string;
        summary: string;
        intro?: string | null;
        programmes?:
          | {
              id: string;
              title: string;
              description: string;
              duration: string;
              mode: string;
              level?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  trainingCategories?:
    | {
        slug: string;
        icon: string;
        title: string;
        tag: string;
        tagTone: 'blue' | 'green' | 'purple' | 'orange';
        summary: string;
        intro?: string | null;
        body?: string | null;
        highlightsTitle?: string | null;
        highlightsNote?: string | null;
        whoCanApply?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        outcomesTitle?: string | null;
        outcomes?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        vision?: string | null;
        missionTitle?: string | null;
        missionItems?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        extraSections?:
          | {
              title: string;
              items?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        disclaimer?: string | null;
        programmes?:
          | {
              id: string;
              title: string;
              description: string;
              duration: string;
              mode: string;
              level?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  archiveFilterLinks: {
    nationalEvents: string;
    internationalEvents: string;
    workshops: string;
    webinars: string;
  };
  trainingChecklist?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  fallbackHubEvents?:
    | {
        id: string;
        slug: string;
        title: string;
        description: string;
        eventType: string;
        eventTypeLabel: string;
        eventNature: 'national' | 'international';
        startDate: string;
        visualTone: 'blue' | 'orange' | 'purple';
        visualIcon: string;
      }[]
    | null;
  fallbackResourcePersons?:
    | {
        name: string;
        title: string;
        initials: string;
        id?: string | null;
      }[]
    | null;
  fallbackGallery?:
    | {
        image?: (number | null) | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the course registration form fields and payment instructions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrationForm".
 */
export interface RegistrationForm {
  id: number;
  formTitle: string;
  formSubtitle?: string | null;
  sections?:
    | {
        title: string;
        description?: string | null;
        fields?:
          | {
              name: string;
              label: string;
              fieldType: 'text' | 'email' | 'tel' | 'textarea' | 'select' | 'date' | 'time' | 'file' | 'number';
              required?: boolean | null;
              placeholder?: string | null;
              /**
               * Comma-separated options for select fields.
               */
              options?: string | null;
              /**
               * Rows for textarea fields.
               */
              rows?: number | null;
              /**
               * Accept attribute for file inputs.
               */
              accept?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  paymentInstructions?: {
    title?: string | null;
    accountName?: string | null;
    accountNumber?: string | null;
    ifsc?: string | null;
    swift?: string | null;
    branchAddress?: string | null;
    upiId?: string | null;
    note?: string | null;
  };
  paymentMethods?:
    | {
        title: string;
        description?: string | null;
        qrCode?: (number | null) | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Student hub resources, exam prep cards, and achievers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentHubContent".
 */
export interface StudentHubContent {
  id: number;
  academicResources?:
    | {
        id: string;
        title: string;
        description: string;
        ctaLabel: string;
        href: string;
        icon: string;
        iconBg: string;
        featured?: boolean | null;
      }[]
    | null;
  examPrep?:
    | {
        id: string;
        badge: string;
        title: string;
        subtitle: string;
        description: string;
        ctaLabel: string;
        href: string;
        watermark: string;
      }[]
    | null;
  ugcNetAchievers?:
    | {
        name: string;
        title?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * UGC-NET / JRF page copy and structured content.
   */
  ugcNetPage?: {
    heroEyebrow?: string | null;
    heroTitlePrefix?: string | null;
    heroTitleHighlight?: string | null;
    heroDescription?: string | null;
    heroCtaLabel?: string | null;
    heroMetricEyebrow?: string | null;
    heroMetricValue?: string | null;
    overviewTitle?: string | null;
    overviewSubtitle?: string | null;
    overviewDescription?: string | null;
    overviewBody?: string | null;
    whyChooseTitle?: string | null;
    whyChooseItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    programmeTitle?: string | null;
    paperOneTitle?: string | null;
    paperOneDescription?: string | null;
    paperTwoTitle?: string | null;
    paperTwoDescription?: string | null;
    benefitsTitle?: string | null;
    benefits?:
      | {
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    learningTitle?: string | null;
    learningFlow?: string | null;
    learningSteps?:
      | {
          label: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    audienceTitle?: string | null;
    audienceItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    audienceNote?: string | null;
    featuresTitle?: string | null;
    features?:
      | {
          feature: string;
          details: string;
          id?: string | null;
        }[]
      | null;
    batchTitle?: string | null;
    batchDetails?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    batchCtaLabel?: string | null;
    registrationTitle?: string | null;
    registrationSteps?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    facultyTitle?: string | null;
    facultyDescription?: string | null;
    resourcesTitle?: string | null;
    resourceItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    supportTitle?: string | null;
    supportDescription?: string | null;
    faqTitle?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    bottomCtaTitle?: string | null;
    bottomCtaDescription?: string | null;
    bottomCtaTagline?: string | null;
    bottomCtaPrimaryLabel?: string | null;
    bottomCtaSecondaryLabel?: string | null;
    bottomCtaContactLabel?: string | null;
    achieversEyebrow?: string | null;
    achieversTitle?: string | null;
    statsValue?: string | null;
    statsDescription?: string | null;
    quickNav?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Student Career Guidance page copy and structured content.
   */
  careerGuidancePage?: {
    heroEyebrow?: string | null;
    heroTitle?: string | null;
    heroHighlight?: string | null;
    heroDescription?: string | null;
    heroBody?: string | null;
    heroNote?: string | null;
    heroCtaLabel?: string | null;
    heroCtaHref?: string | null;
    careersTitle?: string | null;
    careersDescription?: string | null;
    careerPathways?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    careersCtaLabel?: string | null;
    careersCtaHref?: string | null;
    specialisationTitle?: string | null;
    specialisationDescription?: string | null;
    specialisations?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    specialisationPrimaryCtaLabel?: string | null;
    specialisationPrimaryCtaHref?: string | null;
    specialisationSecondaryCtaLabel?: string | null;
    specialisationSecondaryCtaHref?: string | null;
    academicTitle?: string | null;
    academicDescription?: string | null;
    academicSteps?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    academicNote?: string | null;
    skillsTitle?: string | null;
    skillsIntro?: string | null;
    skillsDescription?: string | null;
    skills?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    skillsCtaLabel?: string | null;
    skillsCtaHref?: string | null;
    internshipsTitle?: string | null;
    internshipsIntro?: string | null;
    internshipsDescription?: string | null;
    internships?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    internshipsNote?: string | null;
    internshipsCtaLabel?: string | null;
    internshipsCtaHref?: string | null;
    examsTitle?: string | null;
    examsDescription?: string | null;
    exams?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    examsNote?: string | null;
    examLinks?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    researchTitle?: string | null;
    researchDescription?: string | null;
    researchItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    researchCtaLabel?: string | null;
    researchCtaHref?: string | null;
    finderTitle?: string | null;
    finderIntro?: string | null;
    finderDescription?: string | null;
    finderFormula?: string | null;
    finderDisclaimer?: string | null;
    consultationTitle?: string | null;
    consultationDescription?: string | null;
    consultationTopics?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    consultationDetails?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    consultationCtaLabel?: string | null;
    consultationCtaHref?: string | null;
    journeyTitle?: string | null;
    journeySteps?:
      | {
          label: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
    resourcesTitle?: string | null;
    resourcesDescription?: string | null;
    resources?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    resourcesCtaLabel?: string | null;
    resourcesCtaHref?: string | null;
    faqTitle?: string | null;
    faqs?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
    bottomCtaTitle?: string | null;
    bottomCtaIntro?: string | null;
    bottomCtaDescription?: string | null;
    bottomCtas?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    disclaimer?: string | null;
    quickNav?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  phone?: T;
  email?: T;
  address?: T;
  totalVisitors?: T;
  mapEmbedUrl?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        youtube?: T;
        whatsapp?: T;
        telegram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerSettings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  topBarEnabled?: T;
  topBarLeftText?: T;
  topBarLeftText2?: T;
  topBarLeftText3?:
    | T
    | {
        icon?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  topBarLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  brandTitle?: T;
  brandSubtitle?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  aboutTitle?: T;
  aboutDescription?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        primaryCTALabel?: T;
        primaryCTAUrl?: T;
        secondaryCTALabel?: T;
        secondaryCTAUrl?: T;
        heroImage?: T;
      };
  sectionText?:
    | T
    | {
        featuredCardsHeading?: T;
        servicesHeading?: T;
        servicesDescription?: T;
        eventsHeading?: T;
        eventsDescription?: T;
        aboutHeading?: T;
        aboutDescription1?: T;
        aboutDescription2?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutPage_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heroImage?: T;
      };
  sectionText?:
    | T
    | {
        aboutHeading?: T;
        aboutDescription1?: T;
        aboutDescription2?: T;
        heroEyebrow?: T;
        heroCtaLabel?: T;
        heroCtaHref?: T;
        heroImageAlt?: T;
        rakeshMessage?: T;
        vijayMessage?: T;
        founderMessage?: T;
        visionBadge?: T;
        visionTitle?: T;
        visionBody?: T;
        visionHighlight?: T;
        visionImageAlt?: T;
        missionBadge?: T;
        missionTitle?: T;
        missionBody?: T;
        missionHighlight?: T;
        missionImageAlt?: T;
        purposeBadge?: T;
        purposeTitle?: T;
        purposeBody?: T;
        purposeHighlight?: T;
        purposeImageAlt?: T;
        leadershipTitle?: T;
        leadershipSubtitle?: T;
        committeeTitle?: T;
        committeeSubtitle?: T;
        certificationsTitle?: T;
        certificationsSubtitle?: T;
        certifications?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        valuesTitle?: T;
        valuesSubtitle?: T;
        uniqueTitle?: T;
        uniqueSubtitle?: T;
        uniqueItems?:
          | T
          | {
              text?: T;
              description?: T;
              id?: T;
            };
        activitiesTitle?: T;
        activitiesSubtitle?: T;
        activityItems?:
          | T
          | {
              text?: T;
              description?: T;
              id?: T;
            };
        expertiseTitle?: T;
        expertiseSubtitle?: T;
        expertiseItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        whyChooseTitle?: T;
        whyChooseSubtitle?: T;
        whyChooseItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pillarsTitle?: T;
        pillarsSubtitle?: T;
        qualityEthicsTitle?: T;
        qualityEthicsEyebrow?: T;
        qualityEthicsItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        researchTitle?: T;
        researchEyebrow?: T;
        researchItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        partnershipsTitle?: T;
        partnershipsEyebrow?: T;
        partnershipItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pillarProofLabels?:
          | T
          | {
              text?: T;
              id?: T;
            };
        membershipTitle?: T;
        membershipSubtitle?: T;
        membershipPlans?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              badge?: T;
              dark?: T;
              id?: T;
            };
        membershipCtaLabel?: T;
        membershipAdvantageEyebrow?: T;
        membershipAdvantageTitle?: T;
        membershipReasons?:
          | T
          | {
              text?: T;
              id?: T;
            };
        roadmapTitle?: T;
        roadmapSubtitle?: T;
        roadmapEyebrow?: T;
        roadmapCardTitle?: T;
        roadmapCardBody?: T;
        futureRoadmapItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        awardsTitle?: T;
        awardsSubtitle?: T;
        awardsCallout?: T;
        awardsImageAlt1?: T;
        awardsImageAlt2?: T;
        awardsImageAlt3?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicesPage_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  sectionText?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroHighlight?: T;
        heroDescription?: T;
        heroCtaLabel?: T;
        labStatusLabel?: T;
        labStatusValue?: T;
        labCardCtaLabel?: T;
        infrastructureEyebrow?: T;
        infrastructureTitle?: T;
        infrastructureBody1?: T;
        infrastructureBody2?: T;
        visionTitle?: T;
        visionBody?: T;
        missionTitle?: T;
        missionBody?: T;
        directorateEyebrow?: T;
        directorateTitle?: T;
        directorateSubtitle?: T;
        teamEyebrow?: T;
        teamTitle?: T;
        teamSubtitle?: T;
        catalogEyebrow?: T;
        catalogTitle?: T;
        legalTitle?: T;
        legalSubtitle?: T;
        legalDescription?: T;
        legalCtaLabel?: T;
        legalCtaSubtext?: T;
        kitsEyebrow?: T;
        kitsTitle?: T;
        kitsDescription?: T;
        trainingTitle?: T;
        researchTitle?: T;
        inquiryEyebrow?: T;
        inquiryTitle?: T;
        inquiryDescription?: T;
        priorityHelplineLabel?: T;
        reportVerificationLabel?: T;
        certificationStats?:
          | T
          | {
              label?: T;
              caption?: T;
              id?: T;
            };
        kitCards?:
          | T
          | {
              title?: T;
              icon?: T;
              id?: T;
            };
        legalLinks?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
        researchItems?:
          | T
          | {
              num?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
        trainingCards?:
          | T
          | {
              title?: T;
              desc?: T;
              cta?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmesCatalog_select".
 */
export interface ProgrammesCatalogSelect<T extends boolean = true> {
  educationCategories?:
    | T
    | {
        slug?: T;
        icon?: T;
        title?: T;
        summary?: T;
        intro?: T;
        programmes?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              duration?: T;
              mode?: T;
              level?: T;
            };
        id?: T;
      };
  trainingCategories?:
    | T
    | {
        slug?: T;
        icon?: T;
        title?: T;
        tag?: T;
        tagTone?: T;
        summary?: T;
        intro?: T;
        body?: T;
        highlightsTitle?: T;
        highlightsNote?: T;
        whoCanApply?:
          | T
          | {
              text?: T;
              id?: T;
            };
        outcomesTitle?: T;
        outcomes?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        vision?: T;
        missionTitle?: T;
        missionItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        extraSections?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
            };
        disclaimer?: T;
        programmes?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              duration?: T;
              mode?: T;
              level?: T;
            };
        id?: T;
      };
  archiveFilterLinks?:
    | T
    | {
        nationalEvents?: T;
        internationalEvents?: T;
        workshops?: T;
        webinars?: T;
      };
  trainingChecklist?:
    | T
    | {
        item?: T;
        id?: T;
      };
  fallbackHubEvents?:
    | T
    | {
        id?: T;
        slug?: T;
        title?: T;
        description?: T;
        eventType?: T;
        eventTypeLabel?: T;
        eventNature?: T;
        startDate?: T;
        visualTone?: T;
        visualIcon?: T;
      };
  fallbackResourcePersons?:
    | T
    | {
        name?: T;
        title?: T;
        initials?: T;
        id?: T;
      };
  fallbackGallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrationForm_select".
 */
export interface RegistrationFormSelect<T extends boolean = true> {
  formTitle?: T;
  formSubtitle?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        fields?:
          | T
          | {
              name?: T;
              label?: T;
              fieldType?: T;
              required?: T;
              placeholder?: T;
              options?: T;
              rows?: T;
              accept?: T;
              id?: T;
            };
        id?: T;
      };
  paymentInstructions?:
    | T
    | {
        title?: T;
        accountName?: T;
        accountNumber?: T;
        ifsc?: T;
        swift?: T;
        branchAddress?: T;
        upiId?: T;
        note?: T;
      };
  paymentMethods?:
    | T
    | {
        title?: T;
        description?: T;
        qrCode?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentHubContent_select".
 */
export interface StudentHubContentSelect<T extends boolean = true> {
  academicResources?:
    | T
    | {
        id?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        href?: T;
        icon?: T;
        iconBg?: T;
        featured?: T;
      };
  examPrep?:
    | T
    | {
        id?: T;
        badge?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        ctaLabel?: T;
        href?: T;
        watermark?: T;
      };
  ugcNetAchievers?:
    | T
    | {
        name?: T;
        title?: T;
        photo?: T;
        id?: T;
      };
  ugcNetPage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitlePrefix?: T;
        heroTitleHighlight?: T;
        heroDescription?: T;
        heroCtaLabel?: T;
        heroMetricEyebrow?: T;
        heroMetricValue?: T;
        overviewTitle?: T;
        overviewSubtitle?: T;
        overviewDescription?: T;
        overviewBody?: T;
        whyChooseTitle?: T;
        whyChooseItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        programmeTitle?: T;
        paperOneTitle?: T;
        paperOneDescription?: T;
        paperTwoTitle?: T;
        paperTwoDescription?: T;
        benefitsTitle?: T;
        benefits?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
        learningTitle?: T;
        learningFlow?: T;
        learningSteps?:
          | T
          | {
              label?: T;
              desc?: T;
              id?: T;
            };
        audienceTitle?: T;
        audienceItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        audienceNote?: T;
        featuresTitle?: T;
        features?:
          | T
          | {
              feature?: T;
              details?: T;
              id?: T;
            };
        batchTitle?: T;
        batchDetails?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        batchCtaLabel?: T;
        registrationTitle?: T;
        registrationSteps?:
          | T
          | {
              text?: T;
              id?: T;
            };
        facultyTitle?: T;
        facultyDescription?: T;
        resourcesTitle?: T;
        resourceItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        supportTitle?: T;
        supportDescription?: T;
        faqTitle?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        bottomCtaTitle?: T;
        bottomCtaDescription?: T;
        bottomCtaTagline?: T;
        bottomCtaPrimaryLabel?: T;
        bottomCtaSecondaryLabel?: T;
        bottomCtaContactLabel?: T;
        achieversEyebrow?: T;
        achieversTitle?: T;
        statsValue?: T;
        statsDescription?: T;
        quickNav?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  careerGuidancePage?:
    | T
    | {
        heroEyebrow?: T;
        heroTitle?: T;
        heroHighlight?: T;
        heroDescription?: T;
        heroBody?: T;
        heroNote?: T;
        heroCtaLabel?: T;
        heroCtaHref?: T;
        careersTitle?: T;
        careersDescription?: T;
        careerPathways?:
          | T
          | {
              text?: T;
              id?: T;
            };
        careersCtaLabel?: T;
        careersCtaHref?: T;
        specialisationTitle?: T;
        specialisationDescription?: T;
        specialisations?:
          | T
          | {
              text?: T;
              id?: T;
            };
        specialisationPrimaryCtaLabel?: T;
        specialisationPrimaryCtaHref?: T;
        specialisationSecondaryCtaLabel?: T;
        specialisationSecondaryCtaHref?: T;
        academicTitle?: T;
        academicDescription?: T;
        academicSteps?:
          | T
          | {
              text?: T;
              id?: T;
            };
        academicNote?: T;
        skillsTitle?: T;
        skillsIntro?: T;
        skillsDescription?: T;
        skills?:
          | T
          | {
              text?: T;
              id?: T;
            };
        skillsCtaLabel?: T;
        skillsCtaHref?: T;
        internshipsTitle?: T;
        internshipsIntro?: T;
        internshipsDescription?: T;
        internships?:
          | T
          | {
              text?: T;
              id?: T;
            };
        internshipsNote?: T;
        internshipsCtaLabel?: T;
        internshipsCtaHref?: T;
        examsTitle?: T;
        examsDescription?: T;
        exams?:
          | T
          | {
              text?: T;
              id?: T;
            };
        examsNote?: T;
        examLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        researchTitle?: T;
        researchDescription?: T;
        researchItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        researchCtaLabel?: T;
        researchCtaHref?: T;
        finderTitle?: T;
        finderIntro?: T;
        finderDescription?: T;
        finderFormula?: T;
        finderDisclaimer?: T;
        consultationTitle?: T;
        consultationDescription?: T;
        consultationTopics?:
          | T
          | {
              text?: T;
              id?: T;
            };
        consultationDetails?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        consultationCtaLabel?: T;
        consultationCtaHref?: T;
        journeyTitle?: T;
        journeySteps?:
          | T
          | {
              label?: T;
              desc?: T;
              id?: T;
            };
        resourcesTitle?: T;
        resourcesDescription?: T;
        resources?:
          | T
          | {
              text?: T;
              id?: T;
            };
        resourcesCtaLabel?: T;
        resourcesCtaHref?: T;
        faqTitle?: T;
        faqs?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        bottomCtaTitle?: T;
        bottomCtaIntro?: T;
        bottomCtaDescription?: T;
        bottomCtas?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        disclaimer?: T;
        quickNav?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}