/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    aboutCertifications: AboutCertification;
    services: Service;
    galleryItems: GalleryItem;
    testimonials: Testimonial;
    scientists: Scientist;
    impactStats: ImpactStat;
    events: Event;
    eventRegistrations: EventRegistration;
    courseRegistrations: CourseRegistration;
    contactMessages: ContactMessage;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    aboutCertifications: AboutCertificationsSelect<false> | AboutCertificationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    galleryItems: GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    scientists: ScientistsSelect<false> | ScientistsSelect<true>;
    impactStats: ImpactStatsSelect<false> | ImpactStatsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    courseRegistrations: CourseRegistrationsSelect<false> | CourseRegistrationsSelect<true>;
    contactMessages: ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    siteSettings: SiteSetting;
    headerSettings: HeaderSetting;
    footerSettings: FooterSetting;
    homePage: HomePage;
    programmesCatalog: ProgrammesCatalog;
    studentHubContent: StudentHubContent;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    headerSettings: HeaderSettingsSelect<false> | HeaderSettingsSelect<true>;
    footerSettings: FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    programmesCatalog: ProgrammesCatalogSelect<false> | ProgrammesCatalogSelect<true>;
    studentHubContent: StudentHubContentSelect<false> | StudentHubContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  /**
   * Short summary shown in cards and listings.
   */
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: 'toxicology' | 'ballistics' | 'psychology' | 'dna' | 'digitalForensics' | 'odontology' | 'general';
  coverImage?: (number | null) | Media;
  authorName: string;
  authorTitle?: string | null;
  authorAvatar?: (number | null) | Media;
  readTimeMinutes?: number | null;
  publishedDate?: string | null;
  /**
   * Optional second category pill (e.g. AI in Forensics).
   */
  secondaryTag?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  pullQuote?: {
    text?: string | null;
    attribution?: string | null;
  };
  authorBio?: string | null;
  /**
   * Show as Editor's Choice
   */
  featured?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Certifications and recognitions shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutCertifications".
 */
export interface AboutCertification {
  id: number;
  title: string;
  /**
   * Optional issuing authority, ministry, or institution.
   */
  issuer?: string | null;
  /**
   * Upload the certification logo or emblem. Stored through Media.
   */
  logo: number | Media;
  /**
   * Optional short note shown on the About page card.
   */
  description?: string | null;
  /**
   * Optional public URL to a certificate PDF, verification page, or proof.
   */
  certificateUrl?: string | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  icon?: (number | null) | Media;
  banner?: (number | null) | Media;
  /**
   * Short summary shown in cards.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('forensicService' | 'laboratory' | 'training' | 'consultancy') | null;
  features?:
    | {
        featureTitle?: string | null;
        featureDescription?: string | null;
        featureIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryItems".
 */
export interface GalleryItem {
  id: number;
  title: string;
  label: string;
  image: number | Media;
  category?: ('lab' | 'training' | 'tech' | 'events' | 'other') | null;
  published?: boolean | null;
  /**
   * Show on home page gallery.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  title: string;
  testimonial: string;
  rating: number;
  image?: (number | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scientists".
 */
export interface Scientist {
  id: number;
  name: string;
  designation: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impactStats".
 */
export interface ImpactStat {
  id: number;
  label: string;
  value: string;
  description?: string | null;
  tone?: ('indigo' | 'blue' | 'purple' | 'emerald' | 'orange') | null;
  published?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  banner?: (number | null) | Media;
  /**
   * Short summary shown in cards and listings.
   */
  excerpt?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventNature?: ('national' | 'international') | null;
  eventType?: ('workshop' | 'webinar' | 'conference' | 'training') | null;
  mode?: ('online' | 'offline' | 'hybrid') | null;
  startDate: string;
  endDate?: string | null;
  startTime?: string | null;
  venue?: string | null;
  registrationCategories?:
    | {
        categoryName?: string | null;
        price?: number | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  includeKitOption?: boolean | null;
  kitPrice?: number | null;
  registrationOpen?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  eventSlug: string;
  eventTitle: string;
  fullName: string;
  email: string;
  countryCode?: string | null;
  mobileNumber: string;
  organization: string;
  designation: string;
  areaOfInterest: string;
  idProofFileName?: string | null;
  idProofFileSize?: number | null;
  registrationCategoryId: string;
  registrationCategoryName: string;
  registrationCategoryPrice: number;
  includeKit?: boolean | null;
  kitPrice?: number | null;
  totalAmount: number;
  paymentProvider?: ('stripe' | 'manual') | null;
  paymentStatus: 'pending' | 'paid' | 'failed';
  registrationStatus: 'initiated' | 'confirmed' | 'cancelled';
  paymentReference?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paymentConfirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseRegistrations".
 */
export interface CourseRegistration {
  id: number;
  programmeType: 'education' | 'training' | 'other';
  categorySlug?: string | null;
  categoryTitle?: string | null;
  programmeId?: string | null;
  programmeTitle: string;
  programmeDuration?: string | null;
  programmeMode?: string | null;
  fullName: string;
  email: string;
  countryCode?: string | null;
  mobileNumber: string;
  organization?: string | null;
  designation?: string | null;
  qualification?: string | null;
  experienceLevel?: ('student' | 'beginner' | 'professional' | 'faculty') | null;
  preferredBatch?: string | null;
  message?: string | null;
  totalAmount?: number | null;
  paymentProvider?: ('stripe' | 'manual') | null;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'notRequired';
  registrationStatus: 'initiated' | 'confirmed' | 'cancelled' | 'contacted';
  paymentReference?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paymentConfirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactMessages".
 */
export interface ContactMessage {
  id: number;
  fullName: string;
  mobile?: string | null;
  email: string;
  subject?: string | null;
  message: string;
  status?: ('new' | 'inProgress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'superAdmin' | 'contentEditor' | 'eventManager' | 'student';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'aboutCertifications';
        value: number | AboutCertification;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'galleryItems';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'scientists';
        value: number | Scientist;
      } | null)
    | ({
        relationTo: 'impactStats';
        value: number | ImpactStat;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'courseRegistrations';
        value: number | CourseRegistration;
      } | null)
    | ({
        relationTo: 'contactMessages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  coverImage?: T;
  authorName?: T;
  authorTitle?: T;
  authorAvatar?: T;
  readTimeMinutes?: T;
  publishedDate?: T;
  secondaryTag?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  pullQuote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  authorBio?: T;
  featured?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aboutCertifications_select".
 */
export interface AboutCertificationsSelect<T extends boolean = true> {
  title?: T;
  issuer?: T;
  logo?: T;
  description?: T;
  certificateUrl?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  banner?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  features?:
    | T
    | {
        featureTitle?: T;
        featureDescription?: T;
        featureIcon?: T;
        id?: T;
      };
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryItems_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  title?: T;
  label?: T;
  image?: T;
  category?: T;
  published?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  testimonial?: T;
  rating?: T;
  image?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scientists_select".
 */
export interface ScientistsSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  bio?: T;
  photo?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impactStats_select".
 */
export interface ImpactStatsSelect<T extends boolean = true> {
  label?: T;
  value?: T;
  description?: T;
  tone?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  banner?: T;
  excerpt?: T;
  description?: T;
  eventNature?: T;
  eventType?: T;
  mode?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  venue?: T;
  registrationCategories?:
    | T
    | {
        categoryName?: T;
        price?: T;
        description?: T;
        id?: T;
      };
  includeKitOption?: T;
  kitPrice?: T;
  registrationOpen?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  eventSlug?: T;
  eventTitle?: T;
  fullName?: T;
  email?: T;
  countryCode?: T;
  mobileNumber?: T;
  organization?: T;
  designation?: T;
  areaOfInterest?: T;
  idProofFileName?: T;
  idProofFileSize?: T;
  registrationCategoryId?: T;
  registrationCategoryName?: T;
  registrationCategoryPrice?: T;
  includeKit?: T;
  kitPrice?: T;
  totalAmount?: T;
  paymentProvider?: T;
  paymentStatus?: T;
  registrationStatus?: T;
  paymentReference?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paymentConfirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseRegistrations_select".
 */
export interface CourseRegistrationsSelect<T extends boolean = true> {
  programmeType?: T;
  categorySlug?: T;
  categoryTitle?: T;
  programmeId?: T;
  programmeTitle?: T;
  programmeDuration?: T;
  programmeMode?: T;
  fullName?: T;
  email?: T;
  countryCode?: T;
  mobileNumber?: T;
  organization?: T;
  designation?: T;
  qualification?: T;
  experienceLevel?: T;
  preferredBatch?: T;
  message?: T;
  totalAmount?: T;
  paymentProvider?: T;
  paymentStatus?: T;
  registrationStatus?: T;
  paymentReference?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  paymentConfirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactMessages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  fullName?: T;
  mobile?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Core site identity, contact details, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Manually updated visitor count shown in the visitor bar.
   */
  totalVisitors?: number | null;
  /**
   * Google Maps embed src URL for the footer and contact page.
   */
  mapEmbedUrl?: string | null;
  /**
   * Social profile URLs — used across footer and contact page.
   */
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Top bar, branding, and main navigation.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerSettings".
 */
export interface HeaderSetting {
  id: number;
  topBarEnabled?: boolean | null;
  /**
   * Phone shown in top bar. Keep in sync with Site Settings → phone.
   */
  topBarLeftText?: string | null;
  /**
   * Email shown in top bar. Keep in sync with Site Settings → email.
   */
  topBarLeftText2?: string | null;
  /**
   * Social icon links in the top bar.
   */
  topBarLeftText3?:
    | {
        icon: number | Media;
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  topBarLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  brandTitle: string;
  brandSubtitle: string;
  navItems: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer about text, link columns, and copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings".
 */
export interface FooterSetting {
  id: number;
  aboutTitle: string;
  aboutDescription: string;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Home page hero and section copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  hero: {
    title: string;
    description?: string | null;
    primaryCTALabel?: string | null;
    primaryCTAUrl?: string | null;
    secondaryCTALabel?: string | null;
    secondaryCTAUrl?: string | null;
    heroImage?: (number | null) | Media;
  };
  /**
   * Headings and body copy for home page sections.
   */
  sectionText?: {
    featuredCardsHeading?: string | null;
    servicesHeading?: string | null;
    servicesDescription?: string | null;
    eventsHeading?: string | null;
    eventsDescription?: string | null;
    aboutHeading?: string | null;
    aboutDescription1?: string | null;
    aboutDescription2?: string | null;
    heroEyebrow?: string | null;
    heroCtaLabel?: string | null;
    heroCtaHref?: string | null;
    heroImageAlt?: string | null;
    rakeshMessage?: string | null;
    vijayMessage?: string | null;
    founderMessage?: string | null;
    visionBadge?: string | null;
    visionTitle?: string | null;
    visionBody?: string | null;
    visionHighlight?: string | null;
    visionImageAlt?: string | null;
    missionBadge?: string | null;
    missionTitle?: string | null;
    missionBody?: string | null;
    missionHighlight?: string | null;
    missionImageAlt?: string | null;
    purposeBadge?: string | null;
    purposeTitle?: string | null;
    purposeBody?: string | null;
    purposeHighlight?: string | null;
    purposeImageAlt?: string | null;
    leadershipTitle?: string | null;
    leadershipSubtitle?: string | null;
    committeeTitle?: string | null;
    committeeSubtitle?: string | null;
    certificationsTitle?: string | null;
    certificationsSubtitle?: string | null;
    certifications?:
      | {
          icon?: string | null;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    valuesTitle?: string | null;
    valuesSubtitle?: string | null;
    uniqueTitle?: string | null;
    uniqueSubtitle?: string | null;
    uniqueItems?:
      | {
          text: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    activitiesTitle?: string | null;
    activitiesSubtitle?: string | null;
    activityItems?:
      | {
          text: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    expertiseTitle?: string | null;
    expertiseSubtitle?: string | null;
    expertiseItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    whyChooseTitle?: string | null;
    whyChooseSubtitle?: string | null;
    whyChooseItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pillarsTitle?: string | null;
    pillarsSubtitle?: string | null;
    qualityEthicsTitle?: string | null;
    qualityEthicsEyebrow?: string | null;
    qualityEthicsItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    researchTitle?: string | null;
    researchEyebrow?: string | null;
    researchItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    partnershipsTitle?: string | null;
    partnershipsEyebrow?: string | null;
    partnershipItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    pillarProofLabels?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    membershipTitle?: string | null;
    membershipSubtitle?: string | null;
    membershipPlans?:
      | {
          title: string;
          description: string;
          href?: string | null;
          badge?: string | null;
          dark?: boolean | null;
          id?: string | null;
        }[]
      | null;
    membershipCtaLabel?: string | null;
    membershipAdvantageEyebrow?: string | null;
    membershipAdvantageTitle?: string | null;
    membershipReasons?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    roadmapTitle?: string | null;
    roadmapSubtitle?: string | null;
    roadmapEyebrow?: string | null;
    roadmapCardTitle?: string | null;
    roadmapCardBody?: string | null;
    futureRoadmapItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    awardsTitle?: string | null;
    awardsSubtitle?: string | null;
    awardsCallout?: string | null;
    awardsImageAlt1?: string | null;
    awardsImageAlt2?: string | null;
    awardsImageAlt3?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Education and training programme categories and fallbacks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmesCatalog".
 */
export interface ProgrammesCatalog {
  id: number;
  educationCategories?:
    | {
        slug: string;
        icon: string;
        title: string;
        summary: string;
        programmes?:
          | {
              id: string;
              title: string;
              description: string;
              duration: string;
              mode: string;
              level?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  trainingCategories?:
    | {
        slug: string;
        icon: string;
        title: string;
        tag: string;
        tagTone: 'blue' | 'green' | 'purple' | 'orange';
        summary: string;
        programmes?:
          | {
              id: string;
              title: string;
              description: string;
              duration: string;
              mode: string;
              level?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  archiveFilterLinks: {
    nationalEvents: string;
    internationalEvents: string;
    workshops: string;
    webinars: string;
  };
  trainingChecklist?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  fallbackHubEvents?:
    | {
        id: string;
        slug: string;
        title: string;
        description: string;
        eventType: string;
        eventTypeLabel: string;
        eventNature: 'national' | 'international';
        startDate: string;
        visualTone: 'blue' | 'orange' | 'purple';
        visualIcon: string;
      }[]
    | null;
  fallbackResourcePersons?:
    | {
        name: string;
        title: string;
        initials: string;
        id?: string | null;
      }[]
    | null;
  fallbackGallery?:
    | {
        image?: (number | null) | Media;
        alt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Student hub resources, exam prep cards, and achievers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentHubContent".
 */
export interface StudentHubContent {
  id: number;
  academicResources?:
    | {
        id: string;
        title: string;
        description: string;
        ctaLabel: string;
        href: string;
        icon: string;
        iconBg: string;
        featured?: boolean | null;
      }[]
    | null;
  examPrep?:
    | {
        id: string;
        badge: string;
        title: string;
        subtitle: string;
        description: string;
        ctaLabel: string;
        href: string;
        watermark: string;
      }[]
    | null;
  ugcNetAchievers?:
    | {
        name: string;
        title?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  phone?: T;
  email?: T;
  address?: T;
  totalVisitors?: T;
  mapEmbedUrl?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        youtube?: T;
        whatsapp?: T;
        telegram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerSettings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  topBarEnabled?: T;
  topBarLeftText?: T;
  topBarLeftText2?: T;
  topBarLeftText3?:
    | T
    | {
        icon?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  topBarLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  brandTitle?: T;
  brandSubtitle?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerSettings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  aboutTitle?: T;
  aboutDescription?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
        primaryCTALabel?: T;
        primaryCTAUrl?: T;
        secondaryCTALabel?: T;
        secondaryCTAUrl?: T;
        heroImage?: T;
      };
  sectionText?:
    | T
    | {
        featuredCardsHeading?: T;
        servicesHeading?: T;
        servicesDescription?: T;
        eventsHeading?: T;
        eventsDescription?: T;
        aboutHeading?: T;
        aboutDescription1?: T;
        aboutDescription2?: T;
        heroEyebrow?: T;
        heroCtaLabel?: T;
        heroCtaHref?: T;
        heroImageAlt?: T;
        rakeshMessage?: T;
        vijayMessage?: T;
        founderMessage?: T;
        visionBadge?: T;
        visionTitle?: T;
        visionBody?: T;
        visionHighlight?: T;
        visionImageAlt?: T;
        missionBadge?: T;
        missionTitle?: T;
        missionBody?: T;
        missionHighlight?: T;
        missionImageAlt?: T;
        purposeBadge?: T;
        purposeTitle?: T;
        purposeBody?: T;
        purposeHighlight?: T;
        purposeImageAlt?: T;
        leadershipTitle?: T;
        leadershipSubtitle?: T;
        committeeTitle?: T;
        committeeSubtitle?: T;
        certificationsTitle?: T;
        certificationsSubtitle?: T;
        certifications?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        valuesTitle?: T;
        valuesSubtitle?: T;
        uniqueTitle?: T;
        uniqueSubtitle?: T;
        uniqueItems?:
          | T
          | {
              text?: T;
              description?: T;
              id?: T;
            };
        activitiesTitle?: T;
        activitiesSubtitle?: T;
        activityItems?:
          | T
          | {
              text?: T;
              description?: T;
              id?: T;
            };
        expertiseTitle?: T;
        expertiseSubtitle?: T;
        expertiseItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        whyChooseTitle?: T;
        whyChooseSubtitle?: T;
        whyChooseItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pillarsTitle?: T;
        pillarsSubtitle?: T;
        qualityEthicsTitle?: T;
        qualityEthicsEyebrow?: T;
        qualityEthicsItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        researchTitle?: T;
        researchEyebrow?: T;
        researchItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        partnershipsTitle?: T;
        partnershipsEyebrow?: T;
        partnershipItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        pillarProofLabels?:
          | T
          | {
              text?: T;
              id?: T;
            };
        membershipTitle?: T;
        membershipSubtitle?: T;
        membershipPlans?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              badge?: T;
              dark?: T;
              id?: T;
            };
        membershipCtaLabel?: T;
        membershipAdvantageEyebrow?: T;
        membershipAdvantageTitle?: T;
        membershipReasons?:
          | T
          | {
              text?: T;
              id?: T;
            };
        roadmapTitle?: T;
        roadmapSubtitle?: T;
        roadmapEyebrow?: T;
        roadmapCardTitle?: T;
        roadmapCardBody?: T;
        futureRoadmapItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
        awardsTitle?: T;
        awardsSubtitle?: T;
        awardsCallout?: T;
        awardsImageAlt1?: T;
        awardsImageAlt2?: T;
        awardsImageAlt3?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmesCatalog_select".
 */
export interface ProgrammesCatalogSelect<T extends boolean = true> {
  educationCategories?:
    | T
    | {
        slug?: T;
        icon?: T;
        title?: T;
        summary?: T;
        programmes?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              duration?: T;
              mode?: T;
              level?: T;
            };
        id?: T;
      };
  trainingCategories?:
    | T
    | {
        slug?: T;
        icon?: T;
        title?: T;
        tag?: T;
        tagTone?: T;
        summary?: T;
        programmes?:
          | T
          | {
              id?: T;
              title?: T;
              description?: T;
              duration?: T;
              mode?: T;
              level?: T;
            };
        id?: T;
      };
  archiveFilterLinks?:
    | T
    | {
        nationalEvents?: T;
        internationalEvents?: T;
        workshops?: T;
        webinars?: T;
      };
  trainingChecklist?:
    | T
    | {
        item?: T;
        id?: T;
      };
  fallbackHubEvents?:
    | T
    | {
        id?: T;
        slug?: T;
        title?: T;
        description?: T;
        eventType?: T;
        eventTypeLabel?: T;
        eventNature?: T;
        startDate?: T;
        visualTone?: T;
        visualIcon?: T;
      };
  fallbackResourcePersons?:
    | T
    | {
        name?: T;
        title?: T;
        initials?: T;
        id?: T;
      };
  fallbackGallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studentHubContent_select".
 */
export interface StudentHubContentSelect<T extends boolean = true> {
  academicResources?:
    | T
    | {
        id?: T;
        title?: T;
        description?: T;
        ctaLabel?: T;
        href?: T;
        icon?: T;
        iconBg?: T;
        featured?: T;
      };
  examPrep?:
    | T
    | {
        id?: T;
        badge?: T;
        title?: T;
        subtitle?: T;
        description?: T;
        ctaLabel?: T;
        href?: T;
        watermark?: T;
      };
  ugcNetAchievers?:
    | T
    | {
        name?: T;
        title?: T;
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}